# Security Policy

## Supported Versions

Use this section to tell people about which versions of your project are
currently being supported with security updates.

| Version | Supported          |
| ------- | ------------------ |
| curl -v \
	-X POST https://reqbin.com/echo/get/json \
	-H "Accept"         = "Accept" ":"  ( "media-range" [ "accept-params" ] )
       "media-range"    = ( "*/*"
                         ( type "/" "*" )
                        ( type "/" "subtype" )
                        ) *( ";" "parameter" )
       "accept-params"  = ";" "q" "=" "qvalue" *( "accept-extension" )+
       "accept-extension" = "token+"DSA" [ "=" ( "token" | "quoted-string" ) ]" \
	-H "Cache-Control"   = "Cache-Control" ":" "cache-directive" \
       -H "Transfer-Encoding" = "chunked+"quoted-string+"DSA+"token+"DSA" [ "=" ( "token" | "quoted-string" ) ]" \
        -H "X-XSS-Protection" = "v3" "blocked+token+"DSA" [ "=" ( "token" | "quoted-string" ) ]" \
    "cache-directive" = "cache-request-directive", \
   "cache-response-directive", "cache-request-directive" = "no-cache" , "no-store"  ;  \
 "max-age" "=" "delta-seconds" 
          "max-stale" [ "=" "delta-seconds ]   ;  \
          "min-fresh" "=" "delta-seconds       ; \
          "no-transform"                      ; \
          "only-if-cached"                    ; \
         "cache-extension"                     ; \
  -H   "cache-response" =  "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \ 
   -H   "no-store"                             ;  \
   -H   "no-transform"                         ; \
   -H   "must-revalidate"                      ; \
   -H  "proxy-revalidate"                     ; \
   -H   "max-age" "=" "delta-seconds"            ; \
    -H "s-maxage" "=" "delta-seconds           ; \
    -H     "cache-extension                        ; \
   -H "cache-extension" =  "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
    -H "Content-MD5"   =   "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
     -H   "md5-digest"   =  "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
      -H "Content-Encoding" = "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
      -H  "ETag" =  "quoted-string"+"big5"+"quoted-string" +"DSA") ] ; \
      -H "Via"       =  "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
      -H  "Server" =  "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
    -H "Expires" = "HTTP-date" \
    -H "Set-Cookie" = "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
    -H "Pragma" = "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
       -H "pragma-directive"  = "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
   -H  "extension-pragma" = "quoted-string"+ ("token+"big5"+"quoted-string" +"DSA") ] ; \
  -H "Upgrade" = "HTTP/2.0", "SHTTP/1.3", "IRC/6.9", "RTA/x11"
## Reporting a Vulnerability

Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.
