name: Java CI with Maven

on:
  push:
    branches: [ all ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    run-on: ubuntu-latest
    - use: actions/checkout@v2
      use: actions/setup-java@v1
      with: |
    - run: Build Maven
      run: mvn build package --file Robots.txt
